### ISSUE TITLE
[Util Change]: Strange behaviour using &r on CTG

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/mc-utils#200]
### Util Name

Color Text Generator

### Changes

![image](https://github.com/flytegg/mc-utils/assets/138625055/7879ad7d-e6c2-4eed-8cff-4826d5d41543)

### Extra Info

The combination of #198 and #197. Both work individually but I think some unintended behaviour might have been slipped through when working together

**Comment by Tofpu** [comment]
Good find! I took a look, and it has to do with the `display: inline-block` style, I hated it anyway haha. I don't think there is any other way to remove the inherited decorations with the way we're applying the Minecraft formatting. So instead, I'll try going with an algorithmic approach instead and see how that turns out

**Comment by stephendotgg** [comment]
Fixed thanks to #202
